language: python

python:
  - '3.5'


branches:
  only:
    - staging1

before_script:
  - easy_install distribute
  - pip install -r requirements.txt 

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="plateforme.settings.travis"

script:
  - python env/manage.py test plateforme.tests
