language: python
python:
  - '3.5'

# safelist
branches:
  only:
    - staging1

before_script:
  - pip install --allow-all-external -r requirements.txt 

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="plateforme.settings.travis"

script:
  - ./manage.py test
