# Generated by Django 2.2.1 on 2019-05-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_aliment1', models.CharField(max_length=100)),
                ('name_aliment2', models.CharField(max_length=100)),
                ('name_aliment3', models.CharField(max_length=100)),
                ('name_aliment4', models.CharField(max_length=100)),
                ('name_aliment5', models.CharField(max_length=100)),
                ('name_aliment6', models.CharField(max_length=100)),
            ],
        ),
    ]
