language: python

python:
 - "3.5"
 
# command to install dependencies
before_script:
  - pip install -r requirements.txt
# command to run tests

branches: 
    only:
      - staging 


env: DJANGO_SETTINGS_MODULE = 'plateforme.settings.travis'

services:
  - postgresql 

script:
   - python manage.py test
 

