language: python
python:
      - "3.5"
      - "3.7"
# command to install dependencies
before_script:
      - pip install --allow-all-external -r requirements.txt 
# command to run tests

branches: 
    only:
	 - staging1 


env: DJANGO_SETTINGS_MODULE = 'plateforme.settings.travis'

service:
  - postgresql 

script:
  - python manage.py test

